name: Build
on: [workflow_dispatch, workflow_call, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: linux-x86_64-gnu
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: linux-aarch64-gnu
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - name: windows-x86_64-msvc
            runner: windows-latest
            target: x86_64-pc-windows-msvc
          - name: windows-aarch64-msvc
            runner: windows-latest
            target: aarch64-pc-windows-msvc
          - name: macos-aarch64
            runner: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v6

      - name: Configure Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "${{ matrix.target }}"

      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Linux deps
        if: startsWith(matrix.runner, 'ubuntu-')
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libxdo-dev

      - run: cargo build --verbose --locked --release --target ${{ matrix.target }}

      - name: Prepare binary
        shell: bash
        run: |
          BIN_SUFFIX=""
          if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
            BIN_SUFFIX=".exe"
          fi

          # The built binary output location
          BIN_OUTPUT="target/${{ matrix.target }}/release/mb-tray${BIN_SUFFIX}"

          # Define a better name for the final binary
          BIN_FILENAME="mb-tray-${{ matrix.name }}${BIN_SUFFIX}"

          # Make output directory
          mkdir "${GITHUB_WORKSPACE}/_artifacts"

          # Move the built binary where you want it
          mv "${BIN_OUTPUT}" "${GITHUB_WORKSPACE}/_artifacts/${BIN_FILENAME}"

      - uses: actions/upload-artifact@v7
        with:
          name: mb-tray-${{ matrix.name }}
          path: ${{ github.workspace }}/_artifacts/*
